/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qltour.view;

import java.util.ArrayList;
import qltour.bean.DanhMucBean;
import qltour.controller.changeview_controller;


/**
 *
 * @author nickz
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("Manager Tour");
        changeview_controller controller = new changeview_controller(jpnview);
        controller.setview(jlbmenu,jpnMenu);
        ArrayList<DanhMucBean> list = new ArrayList<>();
        list.add(new DanhMucBean(jlbmenu,"TrangChu"));
        list.add(new DanhMucBean(jlbtour, "Tour"));
        list.add(new DanhMucBean(jlbguest, "Guest"));
        list.add(new DanhMucBean(jlblichtrinh, "LichTrinh"));
        list.add(new DanhMucBean(jlbhopdong, "HopDong"));
        list.add(new DanhMucBean(jlbthongke, "ThongKe"));
        controller.setEven(list);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMenu = new javax.swing.JPanel();
        jlbguest = new javax.swing.JLabel();
        jlbtour = new javax.swing.JLabel();
        jlbhopdong = new javax.swing.JLabel();
        jlblichtrinh = new javax.swing.JLabel();
        jlbhoadon = new javax.swing.JLabel();
        jlbthongke = new javax.swing.JLabel();
        jlbmenu = new javax.swing.JLabel();
        jpnview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(202, 202, 202));
        jpnMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        jlbguest.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlbguest.setForeground(new java.awt.Color(51, 51, 51));
        jlbguest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbguest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/guests.png"))); // NOI18N
        jlbguest.setText("Quản Lý Khách Hàng");
        jlbguest.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jlbtour.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlbtour.setForeground(new java.awt.Color(51, 51, 51));
        jlbtour.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbtour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/tourism.png"))); // NOI18N
        jlbtour.setText("Quản lý Tour");
        jlbtour.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jlbtour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbtourMouseClicked(evt);
            }
        });

        jlbhopdong.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlbhopdong.setForeground(new java.awt.Color(51, 51, 51));
        jlbhopdong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbhopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/contract.png"))); // NOI18N
        jlbhopdong.setText("Quản lý Hợp Đồng");
        jlbhopdong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jlblichtrinh.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlblichtrinh.setForeground(new java.awt.Color(51, 51, 51));
        jlblichtrinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblichtrinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/calendar.png"))); // NOI18N
        jlblichtrinh.setText("Quản Lý Lịch Trình");
        jlblichtrinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jlbhoadon.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlbhoadon.setForeground(new java.awt.Color(51, 51, 51));
        jlbhoadon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/bill.png"))); // NOI18N
        jlbhoadon.setText("Quản Lý Hóa Đơn");
        jlbhoadon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jlbthongke.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlbthongke.setForeground(new java.awt.Color(51, 51, 51));
        jlbthongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/bar-chart.png"))); // NOI18N
        jlbthongke.setText("Thống kê");
        jlbthongke.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jlbmenu.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jlbmenu.setForeground(new java.awt.Color(51, 51, 51));
        jlbmenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/menu.png"))); // NOI18N
        jlbmenu.setText("MENU");
        jlbmenu.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbguest, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(jlbtour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblichtrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbhopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbhoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlbthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jlbmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jlbtour, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jlbguest, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jlblichtrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jlbhopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jlbhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jlbthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnviewLayout = new javax.swing.GroupLayout(jpnview);
        jpnview.setLayout(jpnviewLayout);
        jpnviewLayout.setHorizontalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jpnviewLayout.setVerticalGroup(
            jpnviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbtourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbtourMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbtourMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbguest;
    private javax.swing.JLabel jlbhoadon;
    private javax.swing.JLabel jlbhopdong;
    private javax.swing.JLabel jlblichtrinh;
    private javax.swing.JLabel jlbmenu;
    private javax.swing.JLabel jlbthongke;
    private javax.swing.JLabel jlbtour;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnview;
    // End of variables declaration//GEN-END:variables
}
