/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qltour.view;

/**
 *
 * @author nickz
 */
public class TrangChuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrangChuJPanel
     */
    public TrangChuJPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon_trangchujlb = new javax.swing.JLabel();
        text_trangchu_jLabel = new javax.swing.JLabel();
        card_trangchu_jpl = new javax.swing.JPanel();
        card1_jpl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        card2_jpl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(136, 168, 202));

        icon_trangchujlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_trangchujlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/img_trangchu.png"))); // NOI18N
        icon_trangchujlb.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        text_trangchu_jLabel.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        text_trangchu_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_trangchu_jLabel.setText("WELL COMEBACK!");
        text_trangchu_jLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        card_trangchu_jpl.setLayout(new java.awt.CardLayout());

        card1_jpl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/img_trangchu_slide1.png"))); // NOI18N
        card1_jpl.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 540));

        card_trangchu_jpl.add(card1_jpl, "card2");

        card2_jpl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qltour/images/car2_img_.png"))); // NOI18N
        card2_jpl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 540));

        card_trangchu_jpl.add(card2_jpl, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_trangchu_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(icon_trangchujlb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(card_trangchu_jpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(icon_trangchujlb, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(text_trangchu_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(card_trangchu_jpl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel card1_jpl;
    private javax.swing.JPanel card2_jpl;
    private javax.swing.JPanel card_trangchu_jpl;
    private javax.swing.JLabel icon_trangchujlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel text_trangchu_jLabel;
    // End of variables declaration//GEN-END:variables
}
